# Generated by Django 6.0 on 2025-12-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='action_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
