# Generated by Django 6.0 on 2026-07-03 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_case_action_steps_case_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='gmail_thread_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('email', 'Email')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='case',
            name='vendor_case_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CaseEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=100, unique=True)),
                ('gmail_thread_id', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=500)),
                ('subject_ko', models.CharField(blank=True, max_length=500)),
                ('body_original', models.TextField(blank=True)),
                ('body_ko', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='api.case')),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
    ]
