# Generated by Django 6.0 on 2026-07-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='analyzed_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
