# Generated by Django 6.0 on 2026-07-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_case_analyzed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='device_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='device_serial',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='software_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
