# Generated by Django 6.0 on 2026-07-10 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_roles(apps, schema_editor):
    """기존 계정: staff/superuser -> admin, 나머지 -> engineer (도입 전 실사용자는 팀원)."""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('api', 'UserProfile')
    for user in User.objects.all():
        role = 'admin' if (user.is_staff or user.is_superuser) else 'engineer'
        UserProfile.objects.get_or_create(user=user, defaults={'role': role})


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_case_device_model_case_device_serial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('engineer', 'Engineer'), ('admin', 'Admin')], default='viewer', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(backfill_roles, migrations.RunPython.noop),
    ]
