# Generated by Django 6.0 on 2026-07-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_signuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='related_cases',
            field=models.ManyToManyField(blank=True, to='api.case'),
        ),
    ]
