# Generated by Django 6.0 on 2026-07-20 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_usageevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageevent',
            name='event',
            field=models.CharField(choices=[('login', 'Login'), ('case_list', 'Case List View'), ('case_view', 'Case Detail View'), ('search', 'Search'), ('agent_chat', 'AI Agent Chat'), ('report_download', 'Report Download'), ('gmail_sync', 'Gmail Sync'), ('knowledge_view', 'Knowledge View')], max_length=20),
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('A10', 'A10'), ('Arista', 'Arista'), ('HPE Aruba', 'HPE Aruba'), ('Juniper', 'Juniper')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('problem', models.TextField()),
                ('root_cause', models.TextField(blank=True, default='')),
                ('resolution', models.TextField()),
                ('device_model', models.CharField(blank=True, default='', max_length=100)),
                ('software_version', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'AI Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=10)),
                ('analyzed_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_items', to='api.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
