# Generated by Django 6.0 on 2026-07-20 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usageevent_event_knowledgeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('A10', 'A10'), ('Arista', 'Arista'), ('HPE Aruba', 'HPE Aruba'), ('Juniper', 'Juniper')], max_length=50)),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('sha256', models.CharField(max_length=64)),
                ('page_count', models.IntegerField(default=0)),
                ('chunk_count', models.IntegerField(default=0)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('page_start', models.IntegerField()),
                ('page_end', models.IntegerField()),
                ('text', models.TextField()),
                ('embedding', models.BinaryField()),
                ('embedding_model', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.referencedocument')),
            ],
            options={
                'ordering': ['document_id', 'seq'],
                'indexes': [models.Index(fields=['embedding_model'], name='api_referen_embeddi_401c9e_idx')],
            },
        ),
    ]
