# Generated by Django 6.0 on 2026-07-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_referencedocument_referencechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
