# Generated by Django 6.0 on 2026-07-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_knowledgeitem_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencedocument',
            name='doc_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
