# Generated by Django 6.0 on 2026-07-21 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_chatsession_chatturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='chat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_items', to='api.chatsession'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='event',
            field=models.CharField(choices=[('login', 'Login'), ('case_list', 'Case List View'), ('case_view', 'Case Detail View'), ('search', 'Search'), ('agent_chat', 'AI Agent Chat'), ('report_download', 'Report Download'), ('gmail_sync', 'Gmail Sync'), ('knowledge_view', 'Knowledge View'), ('knowledge_extract', 'Knowledge Extract from Chat')], max_length=20),
        ),
    ]
