# Generated by Django 6.0 on 2026-07-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_knowledgeitem_chat_session_alter_usageevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='knowledge_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
