# Generated by Django 6.0 on 2026-07-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_case_knowledge_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='requested_role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('engineer', 'Engineer')], default='viewer', max_length=10),
        ),
    ]
