# Generated by Django 6.0 on 2026-08-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_signuprequest_requested_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuprequest',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
