# Generated by Django 6.0 on 2026-08-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_signup_instant_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatturn',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
