# Generated by Django 6.0 on 2026-08-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_chatturn_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='caveats',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='environment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='related_refs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='verification',
            field=models.TextField(blank=True, default=''),
        ),
    ]
