# Generated by Django 6.0 on 2026-08-30 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_knowledgeitem_caveats_knowledgeitem_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200)),
                ('vendor', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('topology_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['vendor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=200, unique=True)),
                ('version', models.CharField(blank=True, default='', max_length=50)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('source_port', models.CharField(blank=True, default='', max_length=50)),
                ('source_is_network', models.BooleanField(default=False)),
                ('target', models.CharField(max_length=100)),
                ('target_port', models.CharField(blank=True, default='', max_length=50)),
                ('target_is_network', models.BooleanField(default=False)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.lab')),
            ],
        ),
        migrations.CreateModel(
            name='LabNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eve_id', models.IntegerField()),
                ('net_type', models.CharField(blank=True, default='', max_length=30)),
                ('left', models.IntegerField(default=0)),
                ('top', models.IntegerField(default=0)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='api.lab')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lab',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='api.labserver'),
        ),
        migrations.CreateModel(
            name='LabNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eve_id', models.IntegerField()),
                ('template', models.CharField(blank=True, default='', max_length=50)),
                ('image', models.CharField(blank=True, default='', max_length=120)),
                ('icon', models.CharField(blank=True, default='', max_length=120)),
                ('left', models.IntegerField(default=0)),
                ('top', models.IntegerField(default=0)),
                ('ram', models.IntegerField(default=0)),
                ('cpu', models.IntegerField(default=0)),
                ('ethernet', models.IntegerField(default=0)),
                ('console_url', models.CharField(blank=True, default='', max_length=200)),
                ('running', models.BooleanField(default=False)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.lab')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('lab', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together={('server', 'path')},
        ),
    ]
