# Generated by Django 6.0 on 2026-08-30 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_lab_labserver_lablink_labnetwork_lab_server_labnode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabNodeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=50)),
                ('mgmt_ip', models.CharField(blank=True, default='', max_length=100)),
                ('driver', models.CharField(choices=[('a10_axapi', 'A10 aXAPI'), ('arista_eapi', 'Arista eAPI'), ('linux_ssh', 'Linux (SSH 포트)'), ('none', '확인 안 함')], default='none', max_length=20)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='api.lab')),
            ],
            options={
                'ordering': ['node_name'],
                'unique_together': {('lab', 'node_name')},
            },
        ),
    ]
