# Generated by Django 6.0 on 2026-08-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_labproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='labnetwork',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labnode',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
