# Generated by Django 6.0 on 2026-09-02 07:03

import django.db.models.deletion
from django.db import migrations, models


def backfill_source(apps, schema_editor):
    """FK가 아직 살아 있는 행만 출처를 채운다.

    둘 다 null인 행은 출처 객체가 이미 지워진 옛 지식이다. 케이스 유래였는지
    대화 유래였는지 알 방법이 없으므로 ''(불명)으로 남긴다 — 추측해 채우면
    화면이 신뢰도를 거짓으로 표시하게 된다.
    """
    KnowledgeItem = apps.get_model('api', 'KnowledgeItem')
    KnowledgeItem.objects.filter(case__isnull=False).update(source='case')
    KnowledgeItem.objects.filter(case__isnull=True,
                                 chat_session__isnull=False).update(source='chat')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_labnetwork_display_name_labnode_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='lab_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_items', to='api.labrun'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='source',
            field=models.CharField(blank=True, choices=[('case', '벤더 케이스'), ('lab', '랩 재현'), ('chat', 'AI 도우미 대화'), ('manual', '직접 작성')], default='', max_length=10),
        ),
        migrations.RunPython(backfill_source, migrations.RunPython.noop),
    ]
