# Generated by Django 6.0 on 2026-09-02 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_knowledge_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrun',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_runs', to='api.case'),
        ),
    ]
