# Generated by Django 6.0 on 2026-09-02 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_knowledge_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCommandRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('A10', 'A10'), ('Arista', 'Arista'), ('HPE Aruba', 'HPE Aruba'), ('Juniper', 'Juniper')], max_length=50)),
                ('os_version', models.CharField(blank=True, default='', max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('apply_commands', models.JSONField(default=list)),
                ('verify_command', models.CharField(blank=True, default='', max_length=300)),
                ('verify_contains', models.CharField(blank=True, default='', max_length=300)),
                ('verify_not_contains', models.CharField(blank=True, default='', max_length=300)),
                ('rollback_commands', models.JSONField(default=list)),
                ('search_text', models.TextField(blank=True, default='')),
                ('fingerprint', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('verified', '검증됨'), ('untested', '미검증 (직접 등록)'), ('failed', '실패')], max_length=10)),
                ('verified_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('last_failure', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('run', '랩 실행에서 확인'), ('manual', '직접 등록')], default='run', max_length=10)),
                ('device_model', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_recipes', to=settings.AUTH_USER_MODEL)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='api.labrun')),
            ],
            options={
                'ordering': ['vendor', 'os_version', 'purpose'],
                'unique_together': {('vendor', 'os_version', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='LabNodeFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=100)),
                ('os_version', models.CharField(blank=True, default='', max_length=100)),
                ('device_model', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(choices=[('probe', '장비에서 읽음'), ('image', 'EVE-NG 이미지에서 추정')], default='probe', max_length=10)),
                ('seen_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='api.lab')),
            ],
            options={
                'ordering': ['node_name'],
                'unique_together': {('lab', 'node_name')},
            },
        ),
    ]
