# Generated by Django 6.0 on 2026-09-02 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_lab_command_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='data_subnet',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='LabIpPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mgmt', '관리 IP'), ('data', '시험 트래픽 대역')], max_length=10)),
                ('cidr', models.CharField(blank=True, default='', max_length=50)),
                ('gateway', models.CharField(blank=True, default='', max_length=50)),
                ('ranges', models.JSONField(blank=True, default=list)),
                ('lab_prefix', models.IntegerField(default=24)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_pools', to='api.labserver')),
            ],
            options={
                'unique_together': {('server', 'kind')},
            },
        ),
    ]
