# Generated by Django 6.0 on 2026-09-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_lab_ip_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeitem',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
