"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import re
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the project-root .env file
# (case-flow/.env). Existing shell variables take precedence.
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 운영 전환 시 .env에 DJANGO_SECRET_KEY를 설정할 것.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-nf+jom4-at!bh3m)_a6a#_!jzpekr!7t#d%(vtv7kin$^)xcn_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 사내망의 다른 PC에서 IP로 접근할 수 있도록 허용 (개발용 — 운영 전환 시 도메인으로 제한할 것)
ALLOWED_HOSTS = ['*']

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
# ]
CORS_ALLOW_ALL_ORIGINS = True
# 세션 쿠키 인증: 프론트(:3000)에서 쿠키를 주고받으려면 credentials 허용 필요
CORS_ALLOW_CREDENTIALS = True

# 프론트 origin(포트가 달라 cross-origin)에서 오는 쓰기 요청의 CSRF 검증 허용 목록.
# 사내망 서버 IP가 바뀌면 .env의 CASEFLOW_FRONTEND_ORIGINS에 추가할 것.
# 항목은 'http://IP:포트' 전체 형태 또는 IP만 써도 된다 (http://…:3000으로 보정).
# DHCP 환경은 '192.168.0.*'처럼 마지막 옥텟 와일드카드로 대역 전체를 허용할 수 있다
# (Django의 CSRF_TRUSTED_ORIGINS 와일드카드는 서브도메인 접두사만 지원해서
#  IP 대역은 여기서 1~254로 직접 펼친다).
def _expand_origin_entry(value):
    value = value.strip()
    if not value:
        return []
    m = re.fullmatch(r'(\d+\.\d+\.\d+)\.\*(:\d+)?', value)
    if m:
        prefix, port = m.group(1), m.group(2) or ''
        return [f'{prefix}.{i}{port}' for i in range(1, 255)]
    return [value]


def _normalize_origin(value):
    if '://' not in value:
        host = value
        if ':' not in host:
            host += ':3000'  # 프론트 기본 포트
        value = f'http://{host}'
    return value


CSRF_TRUSTED_ORIGINS = [
    _normalize_origin(host)
    for entry in os.environ.get(
        'CASEFLOW_FRONTEND_ORIGINS',
        'localhost,127.0.0.1,192.168.54.37',
    ).split(',')
    for host in _expand_origin_entry(entry)
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    # 로그인 없이는 어떤 API도 접근 불가 (예외는 뷰에서 AllowAny로 명시)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# 세션 만료: 12시간 (매 요청마다 연장하지 않음)
SESSION_COOKIE_AGE = 12 * 3600

# 계정 발급 요청의 승인 메일 수신자
SIGNUP_APPROVER_EMAIL = os.environ.get('CASEFLOW_SIGNUP_APPROVER_EMAIL',
                                       'jhshin@ubersys.co.kr')
# 승인 링크 유효기간 (초)
SIGNUP_APPROVAL_MAX_AGE = 7 * 24 * 3600


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Gmail integration
# credentials.json: OAuth client downloaded from Google Cloud Console
# token.json: created automatically after the first OAuth consent
GMAIL_CREDENTIALS_FILE = os.environ.get('GMAIL_CREDENTIALS_FILE', str(BASE_DIR / 'credentials.json'))
GMAIL_TOKEN_FILE = os.environ.get('GMAIL_TOKEN_FILE', str(BASE_DIR / 'token.json'))

# Gmail sync filters
# Only fetch mail newer than this many days (0 = no limit).
GMAIL_SYNC_LOOKBACK_DAYS = int(os.environ.get('GMAIL_SYNC_LOOKBACK_DAYS', '30'))
# Mail whose subject contains any of these keywords is labeled
# CaseFlow/Ignored and never registered as a case.
GMAIL_SYNC_EXCLUDE_SUBJECTS = [
    keyword.strip()
    for keyword in os.environ.get(
        'GMAIL_SYNC_EXCLUDE_SUBJECTS',
        'newsletter,webinar,survey,digest,invitation,promotion',
    ).split(',')
    if keyword.strip()
]

# 벤더 도메인이 from/to 어디에도 없어도 수집할 제목 키워드.
# 고객사↔당사 간 케이스 스레드([Caseopen] ...)는 벤더 도메인 매칭에
# 걸리지 않아 이 키워드로 건져낸다.
GMAIL_SYNC_INCLUDE_SUBJECTS = [
    keyword.strip()
    for keyword in os.environ.get('GMAIL_SYNC_INCLUDE_SUBJECTS', 'Caseopen').split(',')
    if keyword.strip()
]

# 사내 그룹 주소 → 벤더 매핑. 벤더 도메인이 없는 메일(고객사↔당사)의
# 수신자/참조에 낀 그룹 주소로 벤더를 추정한다. 값은 Case.VENDOR_CHOICES와
# 일치해야 함. 형식: 'adc@ubersys.co.kr=A10,other@ubersys.co.kr=Arista'
GROUP_VENDOR_HINTS = {
    address.strip().lower(): vendor.strip()
    for address, _, vendor in (
        entry.partition('=')
        for entry in os.environ.get(
            'CASEFLOW_GROUP_VENDOR_HINTS', 'adc@ubersys.co.kr=A10').split(',')
    )
    if address.strip() and vendor.strip()
}

# AI 분석용 API 키 (email translation). 키가 비어 있으면 해당 제공자 모델 사용 불가.
# ANTHROPIC_API_KEY is preferred; CLAUDE_API_KEY is accepted as an alias.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY') or os.environ.get('CLAUDE_API_KEY', '')
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY') or os.environ.get('GEMINI_API_KEY', '')

# 번역/분석 모델 선택 — 사용할 모델 한 줄만 활성화하고 나머지는 주석 처리.
# 모델 이름 접두어(claude-/gpt-/gemini-)로 제공자를 자동 판별해 해당 API 키를 사용한다.
# 환경변수 CASEFLOW_TRANSLATION_MODEL이 설정되어 있으면 그 값이 우선한다.
#
# --- Anthropic Claude (ANTHROPIC_API_KEY / CLAUDE_API_KEY) ---
# _TRANSLATION_MODEL_DEFAULT = 'claude-opus-4-8'        # $5/$25 per 1M tokens — 최고 품질
# _TRANSLATION_MODEL_DEFAULT = 'claude-sonnet-5'        # $3/$15 — 품질/비용 중간
_TRANSLATION_MODEL_DEFAULT = 'claude-haiku-4-5'         # $1/$5 — 최저 비용
#
# --- OpenAI (OPENAI_API_KEY) ---
# _TRANSLATION_MODEL_DEFAULT = 'gpt-5.5'                # $5/$30 — 하이 (플래그십)
# _TRANSLATION_MODEL_DEFAULT = 'gpt-5.4'                # $2.5/$15 — 중간
# _TRANSLATION_MODEL_DEFAULT = 'gpt-5.4-nano'           # $0.2/$1.25 — 로우 (대량 처리용)
#
# --- Google Gemini (GOOGLE_API_KEY / GEMINI_API_KEY, 무료 티어 1,500건/일) ---
# _TRANSLATION_MODEL_DEFAULT = 'gemini-3.5-flash'       # 무료 티어 — Flash (최신 GA)
# _TRANSLATION_MODEL_DEFAULT = 'gemini-3.1-flash-lite'  # 무료 티어 — Flash-Lite (최저 비용)
TRANSLATION_MODEL = os.environ.get('CASEFLOW_TRANSLATION_MODEL', _TRANSLATION_MODEL_DEFAULT)

# 헬프 에이전트 역할별 모델 (합의 매핑: 트리아지·DB검색=haiku, 리포팅·기술지원=sonnet)
# HELP_AGENT_MODEL은 트리아지 분류와 기술지원 답변 검수(평가자)에도 사용된다.
# 기술 조언 품질이 아쉬우면 CASEFLOW_TECH_AGENT_MODEL=claude-opus-4-8 로 상향.
HELP_AGENT_MODEL = os.environ.get('CASEFLOW_HELP_AGENT_MODEL', 'claude-haiku-4-5')
REPORT_AGENT_MODEL = os.environ.get('CASEFLOW_REPORT_AGENT_MODEL', 'claude-sonnet-5')
TECH_AGENT_MODEL = os.environ.get('CASEFLOW_TECH_AGENT_MODEL', 'claude-sonnet-5')

# 기술지원 에이전트의 웹 검색 (Google via Serper)
SERPER_API_KEY = os.environ.get('SERPER_API_KEY', '')

# 웹 검색어에 절대 포함되면 안 되는 용어(고객사명 등) — 코드 레벨 정제.
# 시리얼 번호·사설 IP는 패턴으로 자동 차단되므로 여기엔 이름류만.
SEARCH_BLOCKED_TERMS = [
    term.strip().lower()
    for term in os.environ.get(
        'CASEFLOW_SEARCH_BLOCKED_TERMS',
        'samsung,삼성,nhn,kakao,카카오,하나은행,ubersys,위버시스템즈',
    ).split(',')
    if term.strip()
]
