from django.urls import path
from . import auth_views, views

urlpatterns = [
    path('health/', views.health_check, name='health_check'),
    path('auth/login/', auth_views.LoginView.as_view(), name='auth-login'),
    path('auth/logout/', auth_views.LogoutView.as_view(), name='auth-logout'),
    path('auth/me/', auth_views.MeView.as_view(), name='auth-me'),
    path('auth/users/', auth_views.UserListCreateView.as_view(), name='auth-users'),
    path('auth/signup-requests/', auth_views.SignupRequestView.as_view(),
         name='auth-signup-request'),
    path('auth/signup-approve/', auth_views.SignupApproveView.as_view(),
         name='auth-signup-approve'),
    path('auth/users/<int:user_id>/', auth_views.UserDetailView.as_view(),
         name='auth-user-detail'),
    path('cases/', views.CaseListCreateView.as_view(), name='case-list-create'),
    path('cases/<int:id>/', views.CaseDetailView.as_view(), name='case-detail'),
    path('cases/<int:id>/relations/', views.CaseRelationView.as_view(),
         name='case-relation-add'),
    path('cases/<int:id>/relations/<int:other_id>/', views.CaseRelationView.as_view(),
         name='case-relation-remove'),
    path('knowledge/', views.KnowledgeListView.as_view(), name='knowledge-list'),
    path('knowledge/sync/', views.KnowledgeSyncView.as_view(), name='knowledge-sync'),
    path('knowledge/<int:id>/', views.KnowledgeDetailView.as_view(),
         name='knowledge-detail'),
    path('gmail/sync/', views.GmailSyncView.as_view(), name='gmail-sync'),
    path('help-agent/chat/', views.HelpAgentChatView.as_view(), name='help-agent-chat'),
    path('help-agent/sessions/', views.ChatSessionListView.as_view(),
         name='help-agent-sessions'),
    path('help-agent/sessions/<int:session_id>/', views.ChatSessionDetailView.as_view(),
         name='help-agent-session-detail'),
    path('help-agent/sessions/<int:session_id>/knowledge/',
         views.ChatKnowledgeExtractView.as_view(), name='help-agent-session-knowledge'),
    path('help-agent/files/<str:file_id>/', views.HelpAgentFileView.as_view(),
         name='help-agent-file'),
    path('dashboard/stats/', views.DashboardStatsView.as_view(), name='dashboard-stats'),
    path('usage/', views.UsageEventView.as_view(), name='usage-event'),
    path('usage/stats/', views.UsageStatsView.as_view(), name='usage-stats'),
    path('settings/translation-model/', views.TranslationModelView.as_view(),
         name='translation-model'),
]
