from django.urls import path
from . import auth_views, knowledge_image_views, reference_views, views

urlpatterns = [
    path('health/', views.health_check, name='health_check'),
    path('auth/login/', auth_views.LoginView.as_view(), name='auth-login'),
    path('auth/logout/', auth_views.LogoutView.as_view(), name='auth-logout'),
    path('auth/me/', auth_views.MeView.as_view(), name='auth-me'),
    path('auth/users/', auth_views.UserListCreateView.as_view(), name='auth-users'),
    path('auth/signup-requests/', auth_views.SignupRequestView.as_view(),
         name='auth-signup-request'),
    path('auth/users/<int:user_id>/', auth_views.UserDetailView.as_view(),
         name='auth-user-detail'),
    path('cases/', views.CaseListCreateView.as_view(), name='case-list-create'),
    path('cases/<int:id>/', views.CaseDetailView.as_view(), name='case-detail'),
    path('cases/<int:id>/knowledge/', views.CaseKnowledgeExtractView.as_view(),
         name='case-knowledge-extract'),
    path('cases/<int:id>/relations/', views.CaseRelationView.as_view(),
         name='case-relation-add'),
    path('cases/<int:id>/relations/<int:other_id>/', views.CaseRelationView.as_view(),
         name='case-relation-remove'),
    path('knowledge/', views.KnowledgeListView.as_view(), name='knowledge-list'),
    path('knowledge/sync/', views.KnowledgeSyncView.as_view(), name='knowledge-sync'),
    # 이미지 경로가 <int:id>보다 먼저 와야 'images'가 id로 잡히지 않는다
    path('knowledge/images/<path:name>',
         knowledge_image_views.KnowledgeImageFileView.as_view(),
         name='knowledge-image-file'),
    path('knowledge/<int:id>/images/',
         knowledge_image_views.KnowledgeImageListView.as_view(),
         name='knowledge-images'),
    path('knowledge/<int:id>/', views.KnowledgeDetailView.as_view(),
         name='knowledge-detail'),
    path('references/', reference_views.ReferenceListView.as_view(),
         name='reference-list'),
    path('references/file/', reference_views.ReferenceFileView.as_view(),
         name='reference-file'),
    path('references/upload/', reference_views.ReferenceUploadView.as_view(),
         name='reference-upload'),
    path('references/embed/', reference_views.ReferenceEmbedView.as_view(),
         name='reference-embed'),
    path('settings/reference-auto-embed/',
         reference_views.ReferenceAutoEmbedView.as_view(),
         name='reference-auto-embed'),
    path('gmail/sync/', views.GmailSyncView.as_view(), name='gmail-sync'),
    path('help-agent/chat/', views.HelpAgentChatView.as_view(), name='help-agent-chat'),
    path('help-agent/chat/stream/', views.HelpAgentChatStreamView.as_view(),
         name='help-agent-chat-stream'),
    path('help-agent/attachments/', views.HelpAgentAttachmentView.as_view(),
         name='help-agent-attachments'),
    path('help-agent/sessions/', views.ChatSessionListView.as_view(),
         name='help-agent-sessions'),
    path('help-agent/sessions/<int:session_id>/', views.ChatSessionDetailView.as_view(),
         name='help-agent-session-detail'),
    path('help-agent/sessions/<int:session_id>/knowledge/',
         views.ChatKnowledgeExtractView.as_view(), name='help-agent-session-knowledge'),
    path('help-agent/files/<str:file_id>/', views.HelpAgentFileView.as_view(),
         name='help-agent-file'),
    path('dashboard/stats/', views.DashboardStatsView.as_view(), name='dashboard-stats'),
    path('usage/', views.UsageEventView.as_view(), name='usage-event'),
    path('usage/stats/', views.UsageStatsView.as_view(), name='usage-stats'),
    path('settings/translation-model/', views.TranslationModelView.as_view(),
         name='translation-model'),
    path('settings/knowledge-model/', views.KnowledgeModelView.as_view(),
         name='knowledge-model'),
    path('labs/config/', views.LabConfigView.as_view(), name='lab-config'),
    path('labs/', views.LabListView.as_view(), name='lab-list'),
    path('labs/available/', views.LabAvailableView.as_view(), name='lab-available'),
    path('labs/register/', views.LabRegisterView.as_view(), name='lab-register'),
    path('labs/icons/<str:filename>', views.LabIconView.as_view(), name='lab-icon'),
    path('labs/<int:id>/', views.LabTopologyView.as_view(), name='lab-topology'),
    path('labs/<int:id>/refresh/', views.LabRefreshView.as_view(), name='lab-refresh'),
    path('labs/<int:id>/access/', views.LabAccessView.as_view(), name='lab-access'),
    path('labs/<int:id>/status/', views.LabStatusView.as_view(), name='lab-status'),
    path('labs/<int:id>/power/', views.LabPowerView.as_view(), name='lab-power'),
    path('labs/<int:id>/check/', views.LabCheckView.as_view(), name='lab-check'),
    path('labs/<int:id>/blueprints/', views.LabBlueprintView.as_view(),
         name='lab-blueprints'),
    path('labs/<int:id>/runs/', views.LabRunView.as_view(), name='lab-runs'),
    path('cases/<int:id>/lab-runs/', views.CaseLabRunView.as_view(),
         name='case-lab-runs'),
    path('labs/servers/<int:server_id>/ip-pools/', views.LabIpPoolView.as_view(),
         name='lab-ip-pools'),
    path('labs/recipes/', views.LabRecipeView.as_view(), name='lab-recipes'),
    path('labs/runs/<int:run_id>/', views.LabRunDetailView.as_view(),
         name='lab-run-detail'),
    path('labs/runs/<int:run_id>/knowledge/',
         views.LabRunKnowledgeExtractView.as_view(), name='lab-run-knowledge'),
    path('labs/runs/<int:run_id>/rollback/', views.LabRollbackView.as_view(),
         name='lab-rollback'),
    path('labs/<int:id>/chat/', views.LabChatView.as_view(), name='lab-chat'),
    path('labs/proposals/<int:proposal_id>/', views.LabProposalView.as_view(),
         name='lab-proposal'),
    path('settings/lab-agent-model/', views.LabAgentModelView.as_view(),
         name='lab-agent-model'),
    path('settings/gmail-sync/', views.GmailSyncScheduleView.as_view(),
         name='gmail-sync-schedule'),
]
